name: CI pipeline 




on: push



jobs: 
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@latest

      - name: setup python
        uses: actions/setup-python@latest
        with:
          python-version: '3.11'

      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: run pipeline
        run: |
          dvc repro