name: CI pipeline 




on: push



jobs: 
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install dependencies
        run: |
          pip install -r requirements.txt

    

      - name: Install DVC
        run: |
          pip install dvc dvc-s3  # or any other dvc-* package for your chosen remote

      - name: Set up credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          dvc remote add -d myremote s3://dvc-rem
          dvc remote modify myremote access_key_id $AWS_ACCESS_KEY_ID
          dvc remote modify myremote secret_access_key $AWS_SECRET_ACCESS_KEY

      - name: Clean untracked DVC files
        run: |
          rm -f data/processed/processed_data.csv
          rm -f models/xgboost_model.pkl
          rm -f reports/metrics.json

      - name: Pull DVC data
        run: |
          dvc pull -v  # -v for verbose output



      - name: Debug file structure
        run: |
          pwd
          ls -R
          dvc status

      - name: Debug DVC config
        run: |
          cat .dvc/config
          dvc remote list

      - name: Run pipeline
        run: |
          dvc repro